### ISSUE TITLE
Problema con signIn

### ISSUE THREAD

**Issue by AlexGZC** [mejiaro/rums#1]
Me da error amigo
<img width="848" alt="captura de pantalla 2018-10-08 a la s 20 32 53" src="https://user-images.githubusercontent.com/20145372/46643552-ce543680-cb39-11e8-8390-dcb9318b18a5.png">
 el sign in

**Comment by mejiaro** [comment]
Gracias por submitear tu issue amigo, había un problema con las credenciales de Google pero ya se solucionó.
